[opensearch] Create OpenSearch Security backup
bitergia-analytics/bap-deployment-toolkit pull request #100
Opened 2024-10-18 11:50 UTC by zhquan

This commit creates OpenSearch Security daily backup and uploads them to a GCP bucket, it also allows the restoration of these files configurating `opensearch_security_backup_restore` and `opensearch_security_backup_restore_name` parameters.

docs/deployment_and_config.md updated accordingly.

2024-10-30 16:01 UTC, sduenas requested changes
In overall it looks good but check my comments. I specially would like to change the filename of the backup and see if we can move the part to restore the backup somewhere else.

2024-10-31 16:30 UTC, zhquan commented on ansible/roles/opensearch/tasks/snapshots.yml
> +  when: not opensearch_security_backup_restore
Yes, you are right

2024-10-31 17:03 UTC, zhquan commented on docs/deployment_and_config.md
> +  with the format `backup_%Y-%b-%d_%H-%M-%S.tgz` (e.g. `backup_2024-Oct-18_10-42-37.tgz`).
the `securityadmin.sh` script creates the dump files in that date format, let me see

2024-10-31 21:09 UTC, zhquan commented on docs/deployment_and_config.md
> +  with the format `backup_%Y-%b-%d_%H-%M-%S.tgz` (e.g. `backup_2024-Oct-18_10-42-37.tgz`).
I changed it to `20241018` due to the daily cronjob.

2024-10-31 21:16 UTC, zhquan commented on ansible/roles/opensearch/tasks/security_backup.yml
> +- name: Download OpenSearch Securty backup from GCP bucket
I separated them in another file. Yes, we have also restored indexes from a backup in this same role: https://github.com/bitergia-analytics/bap-deployment-toolkit/blob/main/ansible/roles/opensearch/tasks/snapshots.yml#L92.

2024-11-04 14:29 UTC, sduenas approved these changes
LGTM

2024-11-04 14:30 UTC, merged