Support private and anonymous OpenSearch Dashboards
bitergia-analytics/bap-deployment-toolkit pull request #13
Opened 2023-04-05 15:36 UTC by zhquan

This commit creates a new terraform file in the `bap_env_gcp` module named `opensearch_dashboard_anonymous.tf` to create a machine for OpenSearch Dashboards with anonymous access.

Also, update the Ansible `opensearch_dashboards` role. Depending on whether the hostname belongs to the `opensearch_dashboards` inventory group, it will deploy OpenSearch Dashboards disabling the anonymous user, but if it belongs to the
`opensearch_dashboards_anonymous` inventory group, it will deploy OpenSearch Dashboards with the anonymous user.

2023-04-10 16:32 UTC, sduenas commented on ansible/roles/nginx/defaults/main.yml
> +    opensearch_dashboards_endpoint: "https://{{ hostvars[(groups['opensearch_dashboards'][0])].ansible_default_ipv4.address }}:5601"
Is this the only way to define the endpoint? The problem with this approach is that there's going to be a lot of cut&past of the same string, which is long and prone to error. Can we configure it with another variable, so it's only defined once? (once for the private dashboard and once for the public dashboard).

2023-04-10 16:41 UTC, sduenas requested changes
I think the PR looks good but there are still some parts of it that need some work. Please check my comments.

2023-04-10 16:41 UTC, sduenas commented on ansible/roles/nginx/defaults/main.yml
> +instances:
We should find a better name for `instance`. They are not instances by themselves.

2023-04-10 16:41 UTC, sduenas commented on ansible/roles/nginx/defaults/main.yml
> +    host: "{{ hostvars[(groups['opensearch_dashboards'][0]}}"
We also need to document how to configure this on the ansible documentation files.

2023-04-10 16:41 UTC, sduenas commented on docs/provision.md
> +Special attention to `opensearch_dashboards_node_count` and `opensearch_dashboards_anonymous_node_count`.
This section needs to be reworded. It's not clear what the purpose of it is. It needs a better introduction. I can work on something.

2023-04-14 11:52 UTC, sduenas commented on ansible/roles/nginx/defaults/main.yml
> +##    tenant: private
```suggestion
##    tenant: example
```

2023-04-14 12:10 UTC, sduenas requested changes
We are almost there. It looks good but it needs some minor changes.

2023-04-14 13:11 UTC, zhquan commented on ansible/roles/nginx/defaults/main.yml
> +## opensearch_dashboards_instances:
what about `nginx_virtualhosts`?

```
nginx_virtualhosts:
  - fqdn: example.com
    public: false
    tenant: example
  - fqdn: example-public.com
    public: true
    tenant: example-public
```

2023-04-19 10:21 UTC, zhquan commented on ansible/roles/nginx/defaults/main.yml
> +## opensearch_dashboards_instances:
Done, please review it again

2023-04-19 10:29 UTC, sduenas requested changes
LGTM but there's a conflict on one of the documentation pages. Please fix it and we can merge the PR.

2023-04-25 09:41 UTC, sduenas approved these changes
LGTM

2023-04-25 09:42 UTC, merged